name: fsb
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.2
  - debugpy=1.8.5
  - decorator=5.1.1
  - executing=2.1.0
  - icu=75.1
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libcxx=21.1.6
  - libedit=3.1.20250104
  - libffi=3.5.2
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libsodium=1.0.18
  - libsqlite=3.51.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.8.15
  - python_abi=3.8
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.3.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
      - annotated-types==0.7.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.57.0
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - matplotlib==3.7.5
      - numpy==1.24.4
      - pandas==2.0.3
      - pillow==10.4.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.17.0
      - threadpoolctl==3.5.0
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - xgboost==2.1.4
prefix: /opt/miniconda3/envs/fsb
